<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_barang extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_barang_model');
    } 

    /*
     * Listing of tb_barang
     */
    function index()
    {
        $data['tb_barang'] = $this->Tb_barang_model->get_all_tb_barang();
        
        $data['_view'] = 'tb_barang/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_barang
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('namaBarang_','NamaBarang ','required|max_length[200]');
		$this->form_validation->set_rules('satuanBarang','SatuanBarang','required|max_length[200]');
		$this->form_validation->set_rules('deskripsiBarang','DeskripsiBarang','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'namaBarang_' => $this->input->post('namaBarang_'),
				'satuanBarang' => $this->input->post('satuanBarang'),
				'deskripsiBarang' => $this->input->post('deskripsiBarang'),
            );
            
            $tb_barang_id = $this->Tb_barang_model->add_tb_barang($params);
            redirect('tb_barang/index');
        }
        else
        {            
            $data['_view'] = 'tb_barang/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_barang
     */
    function edit($idBarang)
    {   
        // check if the tb_barang exists before trying to edit it
        $data['tb_barang'] = $this->Tb_barang_model->get_tb_barang($idBarang);
        
        if(isset($data['tb_barang']['idBarang']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('namaBarang_','NamaBarang ','required|max_length[200]');
			$this->form_validation->set_rules('satuanBarang','SatuanBarang','required|max_length[200]');
			$this->form_validation->set_rules('deskripsiBarang','DeskripsiBarang','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'namaBarang_' => $this->input->post('namaBarang_'),
					'satuanBarang' => $this->input->post('satuanBarang'),
					'deskripsiBarang' => $this->input->post('deskripsiBarang'),
                );

                $this->Tb_barang_model->update_tb_barang($idBarang,$params);            
                redirect('tb_barang/index');
            }
            else
            {
                $data['_view'] = 'tb_barang/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_barang you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_barang
     */
    function remove($idBarang)
    {
        $tb_barang = $this->Tb_barang_model->get_tb_barang($idBarang);

        // check if the tb_barang exists before trying to delete it
        if(isset($tb_barang['idBarang']))
        {
            $this->Tb_barang_model->delete_tb_barang($idBarang);
            redirect('tb_barang/index');
        }
        else
            show_error('The tb_barang you are trying to delete does not exist.');
    }
    
}
