<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_jenis_barang extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_jenis_barang_model');
    } 

    /*
     * Listing of tb_jenis_barang
     */
    function index()
    {
        $data['tb_jenis_barang'] = $this->Tb_jenis_barang_model->get_all_tb_jenis_barang();
        
        $data['_view'] = 'tb_jenis_barang/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_jenis_barang
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('namaJenis','NamaJenis','required|max_length[100]');
		$this->form_validation->set_rules('keteranganJenis','KeteranganJenis','required|max_length[250]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'namaJenis' => $this->input->post('namaJenis'),
				'keteranganJenis' => $this->input->post('keteranganJenis'),
            );
            
            $tb_jenis_barang_id = $this->Tb_jenis_barang_model->add_tb_jenis_barang($params);
            redirect('tb_jenis_barang/index');
        }
        else
        {            
            $data['_view'] = 'tb_jenis_barang/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_jenis_barang
     */
    function edit($idJenis)
    {   
        // check if the tb_jenis_barang exists before trying to edit it
        $data['tb_jenis_barang'] = $this->Tb_jenis_barang_model->get_tb_jenis_barang($idJenis);
        
        if(isset($data['tb_jenis_barang']['idJenis']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('namaJenis','NamaJenis','required|max_length[100]');
			$this->form_validation->set_rules('keteranganJenis','KeteranganJenis','required|max_length[250]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'namaJenis' => $this->input->post('namaJenis'),
					'keteranganJenis' => $this->input->post('keteranganJenis'),
                );

                $this->Tb_jenis_barang_model->update_tb_jenis_barang($idJenis,$params);            
                redirect('tb_jenis_barang/index');
            }
            else
            {
                $data['_view'] = 'tb_jenis_barang/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_jenis_barang you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_jenis_barang
     */
    function remove($idJenis)
    {
        $tb_jenis_barang = $this->Tb_jenis_barang_model->get_tb_jenis_barang($idJenis);

        // check if the tb_jenis_barang exists before trying to delete it
        if(isset($tb_jenis_barang['idJenis']))
        {
            $this->Tb_jenis_barang_model->delete_tb_jenis_barang($idJenis);
            redirect('tb_jenis_barang/index');
        }
        else
            show_error('The tb_jenis_barang you are trying to delete does not exist.');
    }
    
}
