<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_menu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_menu_model');
    } 

    /*
     * Listing of tb_menu
     */
    function index()
    {
        $data['tb_menu'] = $this->Tb_menu_model->get_all_tb_menu();
        
        $data['_view'] = 'tb_menu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_menu
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('namaMenu','NamaMenu','required|max_length[100]');
		$this->form_validation->set_rules('menuUrl','MenuUrl','required|max_length[200]');
		$this->form_validation->set_rules('menuDesc','MenuDesc','required|max_length[350]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'namaMenu' => $this->input->post('namaMenu'),
				'menuUrl' => $this->input->post('menuUrl'),
				'menuDesc' => $this->input->post('menuDesc'),
            );
            
            $tb_menu_id = $this->Tb_menu_model->add_tb_menu($params);
            redirect('tb_menu/index');
        }
        else
        {            
            $data['_view'] = 'tb_menu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_menu
     */
    function edit($idMenu)
    {   
        // check if the tb_menu exists before trying to edit it
        $data['tb_menu'] = $this->Tb_menu_model->get_tb_menu($idMenu);
        
        if(isset($data['tb_menu']['idMenu']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('namaMenu','NamaMenu','required|max_length[100]');
			$this->form_validation->set_rules('menuUrl','MenuUrl','required|max_length[200]');
			$this->form_validation->set_rules('menuDesc','MenuDesc','required|max_length[350]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'namaMenu' => $this->input->post('namaMenu'),
					'menuUrl' => $this->input->post('menuUrl'),
					'menuDesc' => $this->input->post('menuDesc'),
                );

                $this->Tb_menu_model->update_tb_menu($idMenu,$params);            
                redirect('tb_menu/index');
            }
            else
            {
                $data['_view'] = 'tb_menu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_menu you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_menu
     */
    function remove($idMenu)
    {
        $tb_menu = $this->Tb_menu_model->get_tb_menu($idMenu);

        // check if the tb_menu exists before trying to delete it
        if(isset($tb_menu['idMenu']))
        {
            $this->Tb_menu_model->delete_tb_menu($idMenu);
            redirect('tb_menu/index');
        }
        else
            show_error('The tb_menu you are trying to delete does not exist.');
    }
    
}
