<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_role extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_role_model');
    } 

    /*
     * Listing of tb_role
     */
    function index()
    {
        $data['tb_role'] = $this->Tb_role_model->get_all_tb_role();
        
        $data['_view'] = 'tb_role/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_role
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('namaRole','NamaRole','required|max_length[100]');
		$this->form_validation->set_rules('keteranganRole','KeteranganRole','required|max_length[100]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'namaRole' => $this->input->post('namaRole'),
				'keteranganRole' => $this->input->post('keteranganRole'),
            );
            
            $tb_role_id = $this->Tb_role_model->add_tb_role($params);
            redirect('tb_role/index');
        }
        else
        {            
            $data['_view'] = 'tb_role/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_role
     */
    function edit($idRole)
    {   
        // check if the tb_role exists before trying to edit it
        $data['tb_role'] = $this->Tb_role_model->get_tb_role($idRole);
        
        if(isset($data['tb_role']['idRole']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('namaRole','NamaRole','required|max_length[100]');
			$this->form_validation->set_rules('keteranganRole','KeteranganRole','required|max_length[100]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'namaRole' => $this->input->post('namaRole'),
					'keteranganRole' => $this->input->post('keteranganRole'),
                );

                $this->Tb_role_model->update_tb_role($idRole,$params);            
                redirect('tb_role/index');
            }
            else
            {
                $data['_view'] = 'tb_role/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_role you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_role
     */
    function remove($idRole)
    {
        $tb_role = $this->Tb_role_model->get_tb_role($idRole);

        // check if the tb_role exists before trying to delete it
        if(isset($tb_role['idRole']))
        {
            $this->Tb_role_model->delete_tb_role($idRole);
            redirect('tb_role/index');
        }
        else
            show_error('The tb_role you are trying to delete does not exist.');
    }
    
}
