<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tr_menu_role extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tr_menu_role_model');
    } 

    /*
     * Listing of tr_menu_role
     */
    function index()
    {
        $data['tr_menu_role'] = $this->Tr_menu_role_model->get_all_tr_menu_role();
        
        $data['_view'] = 'tr_menu_role/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tr_menu_role
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('tglDibuat','TglDibuat','required');
		$this->form_validation->set_rules('idMenu','IdMenu','required|integer');
		$this->form_validation->set_rules('idRole','IdRole','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'idMenu' => $this->input->post('idMenu'),
				'idRole' => $this->input->post('idRole'),
				'tglDibuat' => $this->input->post('tglDibuat'),
            );
            
            $tr_menu_role_id = $this->Tr_menu_role_model->add_tr_menu_role($params);
            redirect('tr_menu_role/index');
        }
        else
        {
			$this->load->model('Tb_menu_model');
			$data['all_tb_menu'] = $this->Tb_menu_model->get_all_tb_menu();

			$this->load->model('Tb_role_model');
			$data['all_tb_role'] = $this->Tb_role_model->get_all_tb_role();
            
            $data['_view'] = 'tr_menu_role/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tr_menu_role
     */
    function edit($idTrMenu)
    {   
        // check if the tr_menu_role exists before trying to edit it
        $data['tr_menu_role'] = $this->Tr_menu_role_model->get_tr_menu_role($idTrMenu);
        
        if(isset($data['tr_menu_role']['idTrMenu']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('tglDibuat','TglDibuat','required');
			$this->form_validation->set_rules('idMenu','IdMenu','required|integer');
			$this->form_validation->set_rules('idRole','IdRole','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'idMenu' => $this->input->post('idMenu'),
					'idRole' => $this->input->post('idRole'),
					'tglDibuat' => $this->input->post('tglDibuat'),
                );

                $this->Tr_menu_role_model->update_tr_menu_role($idTrMenu,$params);            
                redirect('tr_menu_role/index');
            }
            else
            {
				$this->load->model('Tb_menu_model');
				$data['all_tb_menu'] = $this->Tb_menu_model->get_all_tb_menu();

				$this->load->model('Tb_role_model');
				$data['all_tb_role'] = $this->Tb_role_model->get_all_tb_role();

                $data['_view'] = 'tr_menu_role/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tr_menu_role you are trying to edit does not exist.');
    } 

    /*
     * Deleting tr_menu_role
     */
    function remove($idTrMenu)
    {
        $tr_menu_role = $this->Tr_menu_role_model->get_tr_menu_role($idTrMenu);

        // check if the tr_menu_role exists before trying to delete it
        if(isset($tr_menu_role['idTrMenu']))
        {
            $this->Tr_menu_role_model->delete_tr_menu_role($idTrMenu);
            redirect('tr_menu_role/index');
        }
        else
            show_error('The tr_menu_role you are trying to delete does not exist.');
    }
    
}
