<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_jenis_barang_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_jenis_barang by idJenis
     */
    function get_tb_jenis_barang($idJenis)
    {
        return $this->db->get_where('tb_jenis_barang',array('idJenis'=>$idJenis))->row_array();
    }
        
    /*
     * Get all tb_jenis_barang
     */
    function get_all_tb_jenis_barang()
    {
        $this->db->order_by('idJenis', 'desc');
        return $this->db->get('tb_jenis_barang')->result_array();
    }
        
    /*
     * function to add new tb_jenis_barang
     */
    function add_tb_jenis_barang($params)
    {
        $this->db->insert('tb_jenis_barang',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_jenis_barang
     */
    function update_tb_jenis_barang($idJenis,$params)
    {
        $this->db->where('idJenis',$idJenis);
        return $this->db->update('tb_jenis_barang',$params);
    }
    
    /*
     * function to delete tb_jenis_barang
     */
    function delete_tb_jenis_barang($idJenis)
    {
        return $this->db->delete('tb_jenis_barang',array('idJenis'=>$idJenis));
    }
}
