<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_peminjaman_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_peminjaman by idPeminjaman
     */
    function get_tb_peminjaman($idPeminjaman)
    {
        return $this->db->get_where('tb_peminjaman',array('idPeminjaman'=>$idPeminjaman))->row_array();
    }
        
    /*
     * Get all tb_peminjaman
     */
    function get_all_tb_peminjaman()
    {
        $this->db->order_by('idPeminjaman', 'desc');
        return $this->db->get('tb_peminjaman')->result_array();
    }
        
    /*
     * function to add new tb_peminjaman
     */
    function add_tb_peminjaman($params)
    {
        $this->db->insert('tb_peminjaman',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_peminjaman
     */
    function update_tb_peminjaman($idPeminjaman,$params)
    {
        $this->db->where('idPeminjaman',$idPeminjaman);
        return $this->db->update('tb_peminjaman',$params);
    }
    
    /*
     * function to delete tb_peminjaman
     */
    function delete_tb_peminjaman($idPeminjaman)
    {
        return $this->db->delete('tb_peminjaman',array('idPeminjaman'=>$idPeminjaman));
    }
}
