<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_role_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_role by idRole
     */
    function get_tb_role($idRole)
    {
        return $this->db->get_where('tb_role',array('idRole'=>$idRole))->row_array();
    }
        
    /*
     * Get all tb_role
     */
    function get_all_tb_role()
    {
        $this->db->order_by('idRole', 'desc');
        return $this->db->get('tb_role')->result_array();
    }
        
    /*
     * function to add new tb_role
     */
    function add_tb_role($params)
    {
        $this->db->insert('tb_role',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_role
     */
    function update_tb_role($idRole,$params)
    {
        $this->db->where('idRole',$idRole);
        return $this->db->update('tb_role',$params);
    }
    
    /*
     * function to delete tb_role
     */
    function delete_tb_role($idRole)
    {
        return $this->db->delete('tb_role',array('idRole'=>$idRole));
    }
}
