<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tr_menu_role_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tr_menu_role by idTrMenu
     */
    function get_tr_menu_role($idTrMenu)
    {
        return $this->db->get_where('tr_menu_role',array('idTrMenu'=>$idTrMenu))->row_array();
    }
        
    /*
     * Get all tr_menu_role
     */
    function get_all_tr_menu_role()
    {
        $this->db->order_by('idTrMenu', 'desc');
        return $this->db->get('tr_menu_role')->result_array();
    }
        
    /*
     * function to add new tr_menu_role
     */
    function add_tr_menu_role($params)
    {
        $this->db->insert('tr_menu_role',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tr_menu_role
     */
    function update_tr_menu_role($idTrMenu,$params)
    {
        $this->db->where('idTrMenu',$idTrMenu);
        return $this->db->update('tr_menu_role',$params);
    }
    
    /*
     * function to delete tr_menu_role
     */
    function delete_tr_menu_role($idTrMenu)
    {
        return $this->db->delete('tr_menu_role',array('idTrMenu'=>$idTrMenu));
    }
}
